[package]
name = "consul-api-example"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
consul-api = { git = "ssh://git@github.com/bk-rs/consul-rs" }

tokio = { version = "1.6", features = ["macros", "rt-multi-thread"]}

